#!/usr/bin/env bash

PERFEXPERT_HOME=`dirname ${0}`;

# Check if we have PERFEXPERT_HPCDATA_HOME pointing correctly
if [ "x${PERFEXPERT_HPCDATA_HOME}" == "x" ]
then
	echo "The environment variable \${PERFEXPERT_HPCDATA_HOME} was not set, exiting..."
	exit 1
fi

# Check if the jar file exists
if [ -f ${PERFEXPERT_HOME}/bin/perfexpert.jar ]
then
	java -Dlog4j.configuration=file:${PERFEXPERT_HOME}/lib/log4j.properties -cp ${PERFEXPERT_HOME}/bin/perfexpert.jar:${PERFEXPERT_HOME}/lib/* edu.utexas.tacc.perfexpert.PerfExpert ${*};
else
	echo "Could not find ${PERFEXPERT_HOME}/bin/perfexpert.jar, trying to build it";
	echo;

	# Try running the build script
	ant -f ${PERFEXPERT_HOME}/build/build.xml jar;
	echo;

	if [ ${?} != "0" ]
	then
		echo "Build failed. Please correct build problems or place a compiled perfexpert.jar in ${PERFEXPERT_HOME}/lib and try again";
		exit 1;
	else
		echo "Starting PerfExpert...";
		java -Dlog4j.configuration=file:${PERFEXPERT_HOME}/lib/log4j.properties -cp ${PERFEXPERT_HOME}/bin/perfexpert.jar:${PERFEXPERT_HOME}/lib/* edu.utexas.tacc.perfexpert.PerfExpert ${*};
	fi
fi
