#!/usr/bin/env bash

# Constants
HPCTOOLKIT_BIN=/home/ashay/apps/hpctoolkit/bin

# Sanity checks
if [ ${#} -lt 1 ]
then
	echo "USAGE: ${0} [--structure hpcstruct-file] program-name [arguments]"
	exit 1;
fi

hpcstruct_file="";
if [ ${1} = "--structure" ]
then
	hpcstruct_file=${2};
	if [ ${#} -lt 3 ]
	then
		echo "USAGE: ${0} [--structure hpcstruct-file] program-name [arguments]"
		exit 1;
	fi

	if [ ! -f ${hpcstruct_file} ]
	then
		echo "Could not find hpc struct file: ${hpcstruct_file}, try entering the absolute path";
		exit 1;
	fi

	shift; shift;
fi;

program_name=${1};

arguments="";
shift;
if [ "x${*}" != "x" ]
then
	arguments=${*};
fi;

if [ ! -f ${program_name} ]
then
	echo "Could not find file: ${program_name}, try entering the absolute path";
	exit 1;
fi

# Check if the output file already exists
if [ -f "experiment.xml" ]
then
	read -e -r -p "'experiment.xml' already exists. Proceeding further will overwrite this file. Continue? [Y/n] " -n 1 reply;
	if [ "${reply}" != "Y" -a "${reply}" != "y" -a "${reply}" != "" ]
	then
		exit 1;
	fi;
fi;

# Put everything into a temporary directory instead of clobbering the working directory
tempDir=`mktemp -d`;

# Just to be sure, we remove any files which might previously exist
rm -rf ${tempDir}/*;

# Check if we received the HPCStruct file as a parameter
if [ "x${hpcstruct_file}" != "x" ]
then
	# If yes, use it
	cp ${hpcstruct_file} ${tempDir}/hpcstruct;
else
	# Else generate it
	${HPCTOOLKIT_BIN}/hpcstruct --output ${tempDir}/hpcstruct ${program_name};
fi

# Run experiments with different configurations
${HPCTOOLKIT_BIN}/hpcrun --event WALLCLOCK --output ${tempDir}/measurements ${program_name} ${arguments};

${HPCTOOLKIT_BIN}/hpcprof --struct ${tempDir}/hpcstruct --output ${tempDir}/database ${tempDir}/measurements;

# Get the final experiment.xml here
mv ${tempDir}/database/experiment.xml .

# Clean up
rm -rf ${tempDir};
rm -f core;

echo
echo "Run the following command to analyze the measurement data:"
echo "perfexpert 0.1 experiment.xml"
