#!/usr/bin/env sh

# Check if the jar file exists
if [ -f bin/perfexpert.jar ]
then
	java -Dlog4j.configuration=file:`pwd`/lib/log4j.properties -cp `pwd`/bin/perfexpert.jar:`pwd`/lib/* edu.utexas.tacc.perfexpert.PerfExpert ${*};
else
	echo "Could not find `pwd`/bin/perfexpert.jar, trying to build it";
	echo;

	# Try running the build script
	ant -f `pwd`/build/build.xml jar;
	echo;

	if [ ${?} != "0" ]
	then
		echo "Build failed. Please correct build problems or place a compiled perfexpert.jar in `pwd`/lib and try again";
		exit 1;
	else
		echo "Starting PerfExpert...";
		java -Dlog4j.configuration=file:`pwd`/lib/log4j.properties -cp `pwd`/bin/perfexpert.jar:`pwd`/lib/* edu.utexas.tacc.perfexpert.PerfExpert ${*};
	fi
fi
